import type { Job } from "@/lib/types"

export const CAREERS: Job[] = [
  {
    slug: "close-protection-officer",
    title: "Close Protection Officer",
    department: "Executive Protection",
    location: "Lagos, Nigeria",
    type: "full-time",
    description:
      "We are seeking experienced Close Protection Officers to join our growing Executive Protection division in Lagos. Successful candidates will provide personal protection to high-value principals in both low-profile and higher-visibility contexts.",
    requirements: [
      "Minimum 3 years close protection experience",
      "Valid CPO certification (SIA, TSCM, or equivalent)",
      "Former military or law enforcement background preferred",
      "Valid Nigerian driver's licence with advanced driving capability",
      "Excellent interpersonal and communication skills",
      "Ability to work flexible hours including nights and weekends",
    ],
    benefits: [
      "Competitive salary commensurate with experience",
      "Medical and life insurance",
      "Continuous professional development",
      "International deployment opportunities",
      "Pension scheme",
    ],
    postedDate: "2025-04-01",
  },
  {
    slug: "intelligence-analyst",
    title: "Intelligence Analyst",
    department: "Intelligence",
    location: "Port Harcourt, Nigeria",
    type: "full-time",
    description:
      "Our Intelligence Division is looking for a talented Intelligence Analyst to produce high-quality intelligence assessments for corporate and government clients. You will work alongside experienced HUMINT and OSINT specialists.",
    requirements: [
      "Degree in security studies, international relations, or equivalent",
      "3+ years intelligence analysis experience",
      "Proficiency in OSINT tools and methodologies",
      "Strong analytical writing and briefing skills",
      "Knowledge of the Niger Delta and West African security environment",
      "Ability to maintain strict confidentiality",
    ],
    benefits: [
      "Competitive remuneration package",
      "Medical cover for self and family",
      "Training and certification support",
      "Flexible working arrangements",
      "Annual performance bonus",
    ],
    postedDate: "2025-03-20",
  },
  {
    slug: "maritime-security-officer",
    title: "Maritime Security Officer",
    department: "Maritime",
    location: "Port Harcourt, Nigeria",
    type: "full-time",
    description:
      "Sokari Securities is recruiting Maritime Security Officers for vessel escort and port security operations in the Gulf of Guinea. This is an operational role requiring fitness, professionalism, and comfort in maritime environments.",
    requirements: [
      "STCW Basic Safety Training certification",
      "Anti-piracy or vessel protection operator qualification",
      "Former Nigerian Navy, Coast Guard, or equivalent background preferred",
      "Physical fitness to meet operational deployment standards",
      "Valid NIMASA-approved certification",
      "Strong situational awareness and calm under pressure",
    ],
    benefits: [
      "Competitive operational pay with deployment allowances",
      "Full kit and equipment provided",
      "Regular leave rotation",
      "Medical cover",
      "Career progression to Senior MSO and Team Leader",
    ],
    postedDate: "2025-03-10",
  },
  {
    slug: "security-risk-consultant",
    title: "Security Risk Consultant",
    department: "Risk Management",
    location: "Abuja / Lagos (Hybrid)",
    type: "full-time",
    description:
      "We are looking for a Security Risk Consultant to develop and deliver security risk assessments, business continuity plans, and crisis management frameworks for our corporate client base.",
    requirements: [
      "Degree in security management, risk management, or equivalent",
      "Professional certification: CPP, CSMP, CISM, or equivalent",
      "5+ years experience in corporate security or risk consulting",
      "Strong client-facing and report writing skills",
      "Experience with ISO 31000 or similar risk frameworks",
      "Ability to travel throughout Nigeria and occasionally West Africa",
    ],
    benefits: [
      "Senior-level remuneration",
      "Performance bonus structure",
      "Medical, dental, and life insurance",
      "Flexible hybrid working",
      "CPD budget and certification support",
    ],
    postedDate: "2025-02-28",
  },
  {
    slug: "security-officer-lagos",
    title: "Security Officer (Lagos)",
    department: "Physical Security",
    location: "Lagos, Nigeria",
    type: "full-time",
    description:
      "We have multiple Security Officer positions available for corporate facility deployments across Lagos Island and Mainland. Candidates must hold a valid NSCDC licence.",
    requirements: [
      "Valid NSCDC security guard licence",
      "Minimum OND or equivalent qualification",
      "At least 2 years manned guarding experience",
      "Physically fit and presentable",
      "Good communication skills",
      "Ability to work rotating shifts",
    ],
    benefits: [
      "Competitive monthly salary",
      "Uniform and equipment provided",
      "Group life insurance",
      "Career development pathway to supervisory roles",
      "Monthly performance incentives",
    ],
    postedDate: "2025-04-10",
  },
]
