import type { Review } from "@/lib/types"

export const REVIEWS: Review[] = [
  {
    id: "r1",
    reviewer: "James Okafor",
    title: "Head of Group Security",
    company: "First Continental Bank",
    rating: 5,
    body: "Sokari Securities transformed our threat posture. Their intelligence products are actionable, timely, and have prevented several serious incidents. The team is genuinely world-class — professional, discreet, and deeply knowledgeable about the Nigerian operating environment.",
    category: "intelligence",
    date: "2025-01-15",
  },
  {
    id: "r2",
    reviewer: "Ambassador R. Thornton",
    title: "Senior Diplomatic Officer",
    company: "EU Mission Nigeria",
    rating: 5,
    body: "During a particularly volatile period, Sokari's executive protection team was outstanding. Their situational awareness, professionalism, and ability to operate under diplomatic protocols made them a seamless extension of our mission team.",
    category: "executive-protection",
    date: "2024-11-30",
  },
  {
    id: "r3",
    reviewer: "Charles Adewale",
    title: "Operations Director",
    company: "TotalEnergies EP Nigeria",
    rating: 5,
    body: "Our offshore operations in the Gulf of Guinea are in safe hands. Sokari's maritime security capability is unmatched in the region — deep knowledge of the threat environment, credible deterrence, and an always-responsive team on the ground.",
    category: "physical-security",
    date: "2024-10-20",
  },
  {
    id: "r4",
    reviewer: "Dr. Ngozi Eze",
    title: "Chief Risk Officer",
    company: "Pinnacle Holdings",
    rating: 5,
    body: "The security risk assessment Sokari delivered for our Lagos campus was thorough and entirely practical. They understood our business context, not just the security theory, and the recommendations were implementable within our budget.",
    category: "risk-consulting",
    date: "2024-09-12",
  },
  {
    id: "r5",
    reviewer: "Michael Brennan",
    title: "Country Manager",
    company: "Helix Construction Ltd",
    rating: 5,
    body: "Reliable, professional, and always ahead of the threat curve. Sokari has been our trusted security partner for over five years across multiple construction projects. They understand what a site needs and deliver without drama.",
    category: "physical-security",
    date: "2024-08-05",
  },
  {
    id: "r6",
    reviewer: "Fatima Al-Rashid",
    title: "Regional Security Manager",
    company: "Meridian Shipping",
    rating: 5,
    body: "We engaged Sokari for vessel escort operations and port security consulting. Their maritime team demonstrated exceptional professionalism and technical capability. The ISPS compliance review was particularly valuable.",
    category: "physical-security",
    date: "2024-07-19",
  },
  {
    id: "r7",
    reviewer: "Tunde Fashola",
    title: "VP Group Operations",
    company: "Sterling Energy Group",
    rating: 4,
    body: "Solid security partner across our Port Harcourt operations. Response times are excellent, the guard force is well-trained and presentable, and the management team is responsive. Would confidently recommend to anyone looking for physical security in the Niger Delta.",
    category: "physical-security",
    date: "2024-06-28",
  },
  {
    id: "r8",
    reviewer: "Claire Hutchings",
    title: "Head of Corporate Affairs",
    company: "British Business Group Nigeria",
    rating: 5,
    body: "Sokari's travel security briefings for our members are consistently excellent — well-researched, current, and presented by people who clearly know the country deeply. They've become our go-to security resource for all Nigeria-related advice.",
    category: "risk-consulting",
    date: "2024-05-15",
  },
  {
    id: "r9",
    reviewer: "Chukwuemeka Igwe",
    title: "Managing Director",
    company: "Igwe & Associates",
    rating: 5,
    body: "After a threat was made against my family, Sokari assembled a protection team overnight. Within 24 hours I had professional close protection in place and a full threat assessment completed. Their speed and professionalism in a crisis is remarkable.",
    category: "executive-protection",
    date: "2024-04-03",
  },
]
